#!/bin/bash

########################
#                      #
# Scheduler Directives #
#                      #
########################

### Set the name of the job, where jobname is a unique name for your job
#PBS -N DB_test

### Select the shell you would like the script to execute within
#PBS -S /bin/bash

### Inform the scheduler of the expected runtime, where walltime=HH:MM:SS
#PBS -l walltime=5:00:00

### Inform the scheduler of the number of CPU cores for your job.
#PBS -l nodes=1:ppn=1

### Inform the scheduler of the amount of memory you expect to use.
### Use units of 'b', 'kb', 'mb', or 'gb'
#PBS -l mem=24gb

### Set the destination for your program's output.
#PBS -o $HOME/DB_test.out
#PBS -e $HOME/DB_test.err


#################
#               #
# Job Execution #
#               #
#################

# Load the approprite applications
module load gcc/6.2.0
module load R/3.3.2

# Reset TMP file location
export TMP=/scratch/jmihaljevic1/tempfiles/HPV/

# Execute the program
R CMD BATCH --no-save /scratch/jmihaljevic1/HPV/code/R/test_db.R
