\documentclass{article}

\title{Dynamic metacommunity model to evaluate HPV strain interactions}
\author{Joe Mihaljevic}

\usepackage{geometry}
\geometry{legalpaper, portrait, margin=.75in}

\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle

\section*{Introduction}

The goal of this project is to create a dynamic, statistical, metacommunity model that estimates correlations among species' persistence and colonization probabilities. This will allow for inference into which species may ecologically interact via priority effects, facilitation, or competition. We will then apply this model to a data set of HPV co-infection dynamics across a large number of patients (i.e. patches). The main novelties of this project are: (1) that we have a unique data set with many HPV strains across a large number of patients, and (2) that this is the first stastistical metacommunity model that estimates pair-wise correlations in the probabilities of colonization and persistence.

\section*{Model Specification}

Here we will outline the dynamic, statistical metacommunity model. This model is based off of Dorazio et al. 2010, Ecology. Importantly, this model does not include the estimation of probability of detection, which corresponds in Dorazio 2010 to the probability of observing rare species. \emph{However, detection probability could later be incorporated in our model to reflect the sensitivity and specificity of HPV genotype testing}.

Our data set consists of $K$ number of patients, who have been scored for the binomial occupancy of $I = 37$ number of HPV strains over $T_{k}$ number of visits, where $T_{k}$ is allowed to vary among patients. Thus the data are of type $y_{ikt}$, which simply consists of a 0 or 1, depending on whether HPV strain $i$ was present in patient $k$ on visit $t$. 

First, we must estimate the initial occupancy probability for each HPV strain, which will then be used in a Markov Process to estimate how strain occupancy changes within and among individuals through time. 
$$y_{ik1} \sim Bern(\psi_{ik1})$$
$\psi_{ik1}$ estimates the probability that strain $i$ occupies patient $k$ at the patient's first visit. For now, we will assume that this initial occupancy probability is strain-specific and proportional to each strain's overall occcurance, but is not affected by any specific covariates. Then, the occupancy probabilities for all subsequent visits depend upon the occupancy status of the previous visit, as follows:

$$y_{ik,t+1} \sim Bern(\psi_{ik,t+1})$$
$$\psi_{ik,t+1} = \phi_{ikt}\psi_{ikt} + \gamma_{ikt}(1-\psi_{ikt})$$

In this formulation, the likelihood of a patient retaining HPV strain $i$ from one visit to the next depends upon the probability of strain $i$ being present at the previous visit, $\psi_{ikt}$, multiplied by the strain-, patient- and time-specific probability of persistence, $\phi_{ikt}$. This persistence probability can also be usefully thought of in terms of an extinction probability, $\xi_{ikt} = 1 - \phi_{ikt}$. Then, the probability that a patient $k$, who is previously uninfected with HPV strain $i$, subsequently becomes infected by strain $i$ at time $t+1$ is determined by the colonization probability, $\gamma_{ikt}$.

\subsubsection*{Covariate effects and correlations}

One of our main goals is to determine how strain interactions might affect the ability of a given strain to colonize a new host or to persist in a host. However, we also want to control for the fact that certain strains may respond similarly to certain characteristics of the host environment. For example, if HPV strains A and B both favor young men, we would like to control for this common response when estimating how strain A might affect strain B's colonization probability. In order to account for strain responses to covariates and to simultaneosly estimate covariance among strains, we estimate colonization and persistence probabilities in the following way. For clarity, we will only present the model for persistence probability, although colonization probability is modeled in the same way. 

$$ logit(\phi_{ikt}) = \alpha_i + \textbf{B}_{i}\textbf{X}_{k} + \textbf{B}^{k}_{i}\textbf{X}_{t[k]} $$

This is a multi-level model in which patients have variable numbers of visits and some covariates are measured at the patient level and are static throughout the survey period, while other covariates are dynamic through time. Importantly, the structure of the data makes it easy to incorporate time-varying covariates in this framework, as the full set of covariates are measured at each visit, and time is indexed by visit number. In the above expression, $\alpha_i$ is the strain-specific baseline persistence probability, given average covariate values. $ \textbf{B}_{i} = (b_{\phi0i}, b_{1i}, \dots, b_{qi})^{'} $ for $q$ number of covariate effects measured at the patient level that do not change across visits. Thus, $ \textbf{X}_{k} = (1, x_{1k}, x_{2k}, \dots, x_{qk}) $ holds the patient-level values of these covariates. 

The next component of the model contains $ \textbf{B}^{k}_{i} = (b^k_{\phi1i}, b^k_{1i}, \dots, b^k_{ri})^{'} $. These are strain-specific responses to covariates, $(1,...,r-1)$, that were measured at the patient-level. However, these covariates, $ \textbf{X}_{t[k]} = (1, x_{1t[k]}, x_{2t[k]}, \dots, x_{rt[k]}) $, are those covariates which were measured at the patient level and potentially have unique values for each patient visit $t$.


We account for correlations between strains' colonization and persistence probabilities among and within patientsby drawing random effects $b_0$ and $b^k_1$ from multivariate normal distributions.

$$ b_0 \sim N(0, \Sigma_{b_{0}}), $$

where $\Sigma_{b_{0}}$ is a covariance matrix, which accounts for among-patient correlations between strains' persistence and colonization probabilities. As the simplest example, in a two-strain scenario:

$$ \Sigma_{b_{0}} = \left[
                \begin{array}{cccc}
                
                %' First row:
                \sigma_{\phi_1}^2 & 
                \rho_{\phi_{1}\phi_{2}}\sigma_{\phi_1}\sigma_{\phi_2} & 
                \rho_{\phi_{1}\gamma_{1}}\sigma_{\phi_1}\sigma_{\gamma_1} & 
                \rho_{\phi_{1}\gamma_{2}}\sigma_{\phi_1}\sigma_{\gamma_2}  \\
                %' Second row:
                \rho_{\phi_{1}\phi_{2}}\sigma_{\phi_1}\sigma_{\phi_2} &
                \sigma_{\phi_2}^2 &
                \rho_{\phi_{2}\gamma_{1}}\sigma_{\phi_2}\sigma_{\gamma_1} & 
                \rho_{\phi_{2}\gamma_{2}}\sigma_{\phi_2}\sigma_{\gamma_2} \\ 
                %' Third row:
                \rho_{\phi_{1}\gamma_{1}}\sigma_{\phi_1}\sigma_{\gamma_1} &
                \rho_{\phi_{2}\gamma_{1}}\sigma_{\phi_2}\sigma_{\gamma_1} & 
                \sigma_{\gamma_1}^2 & 
                \rho_{\gamma_{1}\gamma_{2}}\sigma_{\gamma_1}\sigma_{\gamma_2} \\
                %' Fourth row:
                \rho_{\phi_{1}\gamma_{2}}\sigma_{\phi_1}\sigma_{\gamma_2} &
                \rho_{\phi_{2}\gamma_{2}}\sigma_{\phi_2}\sigma_{\gamma_2} &
                \rho_{\gamma_{1}\gamma_{2}}\sigma_{\gamma_1}\sigma_{\gamma_2} &
                \sigma_{\gamma_2}^2

                \end{array}
                \right]
$$
Here $\sigma_{\phi_1}^2$ is the variance in persistence probability for strain $1$ across all patient samples, and so on. Similarly:

$$ b^k_1 \sim N(0, \Sigma_{b^k_{1}}), $$

In this case, the variances on the diagonal of $\Sigma_{b^k_{1}}$ represent the within-patient variability in persistence and colonization probabilities.

Our model therefore estimates both the among-patient and within-patient strain correlations in persistence and colonization probabilities. It is important to distinguish these among- and within-patient effects because the correlations among strains may be scale-dependent, with different processes leading to different patterns between the two scales (i.e. Simpson's paradox). For example, across all patients and visits, strains A and B may have positively correlated colonization probabilities resulting from the fact that both strain A and B tend to only be able to infect immuno-compromised individuals. However, within a patient, the strains' persistence or colonization probabilities might be negatively correlated if previous infection with strain A hinders the ability of strain B to superinfect. 

\section*{Simulation as proof of concept}

Here we will show that our model works in the sense that we can recover imposed parameters from simulated data. 

The \texttt{sim\_func()} function simulates the occurrence of two HPV strains across a pre-determined number of patients and visits. The function allows us to manipulate many parameters including the strengths of within- and among-patient correlations in persistence and colonization. It also includes one patient-level and one visit-level covariate, the effects of which can be manipulated for each strain.

This is a simulated 'null' case in which we impose no correlations, and no covariate effects. 
<<>>=
source("sim_func.R")

null <- sim_func(n.pat = 100,
                 n.vis = 10, 
                 # Within and among host covariate effects for phi and gamma:
                 bpat1g = 0, 
                 bpat2g = 0,
                 btime1g = 0,
                 btime2g = 0,
                 bpat1p = 0,
                 bpat2p = 0,
                 btime1p = 0,
                 btime2p = 0,
                 # Correlations:
                 manual = 1,
                 # If 'manual' == T, then specify correlations
                 ## Among-patients:
                 raG1G2 = 0,
                 raP1P2 = 0, 
                 raP1G1 = 0,
                 raP2G2 = 0,
                 raP1G2 = 0,
                 raP2G1 = 0,
                 ## Within-patients:
                 rwG1G2 = 0,
                 rwP1P2 = 0, 
                 rwP1G1 = 0,
                 rwP2G2 = 0,
                 rwP1G2 = 0,
                 rwP2G1 = 0,
                 ## sd across patients for each strain (phi and gamma):
                 ## Assume all sd equal
                 sa = 1,
                 ## sd within patients for each strain (phi and gamma):
                 ## Assume all sd equal
                 sw = .4,
                 # If 'manual' == FALSE, generate pos. definite covariance matrix automatically
                 ## eta controls the degree of correlation:
                 etaA = 2, # Among-patient eta
                 etaW = 2, # Within-patient eta
                 #Global probabilities:
                 globphi = .5, 
                 globgam = .5, 
                 globpsi = .5 )
@
This allows you to see all of the function's options, and you can see that the correlations are all set to zero.

Now we can view the correlations in $\gamma$ and $\phi$, and the induced correlations in $\psi$. The null example should have no such correlations.

\begin{center}
<<fig=T, echo=F, height=2, width=10>>=
library(ggplot2)
n1 <- subset(null, Strain == 1)[,2:4]
n2 <- subset(null, Strain == 2)[,2:4]

df <- cbind(n1,n2)
colnames(df) <- c("psi1", "phi1", "gam1", "psi2", "phi2", "gam2")
df <- data.frame(df)


p1 <- qplot(x=phi1, y=phi2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(phi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p2 <- qplot(x=gam1, y=gam2, data=df, geom="point",
            xlab = expression(paste(gamma, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p3 <- qplot(x=phi1, y=gam2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1), breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p4 <- qplot(x=phi2, y=gam1, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 2")),
            ylab = expression(paste(gamma, " Strain 1")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p5 <- qplot(x=psi1, y=psi2, data=df, geom="point",
            xlab = expression(paste(psi, " Strain 1")),
            ylab = expression(paste(psi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

library(gridExtra)
grid.arrange(p1,p2,p3,p4,p5, nrow=1)
@
\end{center}

Let's assume a strong negative correlation in among-patient persistence of strain 1 ($\phi_1$) and colonization of strain 2 ($\gamma_2$). This would represent a situation in which, across all patients, the presence of strain one hinders the colonization of strain 2, a strong priority effect. 
<<>>=
corr1 <- sim_func(raP1G2 = -0.9)
@

\begin{center}
<<fig=T, echo=F, height=2, width=10>>=
library(ggplot2)
n1 <- subset(corr1, Strain == 1)[,2:4]
n2 <- subset(corr1, Strain == 2)[,2:4]

df <- cbind(n1,n2)
colnames(df) <- c("psi1", "phi1", "gam1", "psi2", "phi2", "gam2")
df <- data.frame(df)


p1 <- qplot(x=phi1, y=phi2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(phi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p2 <- qplot(x=gam1, y=gam2, data=df, geom="point",
            xlab = expression(paste(gamma, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p3 <- qplot(x=phi1, y=gam2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1), breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p4 <- qplot(x=phi2, y=gam1, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 2")),
            ylab = expression(paste(gamma, " Strain 1")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p5 <- qplot(x=psi1, y=psi2, data=df, geom="point",
            xlab = expression(paste(psi, " Strain 1")),
            ylab = expression(paste(psi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

library(gridExtra)
grid.arrange(p1,p2,p3,p4,p5, nrow=1)
@
\end{center}

If we have have more than one among-patient correlations that have similar sign, then we see strong induced correlation in $\psi$.

<<>>=
corr2 <- sim_func(raP2G1 = -0.9, raP1G2 = -0.9)
@

\begin{center}
<<fig=T, echo=F, height=2, width=10>>=
library(ggplot2)
n1 <- subset(corr2, Strain == 1)[,2:4]
n2 <- subset(corr2, Strain == 2)[,2:4]

df <- cbind(n1,n2)
colnames(df) <- c("psi1", "phi1", "gam1", "psi2", "phi2", "gam2")
df <- data.frame(df)


p1 <- qplot(x=phi1, y=phi2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(phi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p2 <- qplot(x=gam1, y=gam2, data=df, geom="point",
            xlab = expression(paste(gamma, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p3 <- qplot(x=phi1, y=gam2, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 1")),
            ylab = expression(paste(gamma, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1), breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p4 <- qplot(x=phi2, y=gam1, data=df, geom="point",
            xlab = expression(paste(phi, " Strain 2")),
            ylab = expression(paste(gamma, " Strain 1")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

p5 <- qplot(x=psi1, y=psi2, data=df, geom="point",
            xlab = expression(paste(psi, " Strain 1")),
            ylab = expression(paste(psi, " Strain 2")))+ 
      scale_y_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      scale_x_continuous(limits=c(0,1),breaks=c(0,.5,1))+
      theme(axis.title = element_text(size=18), axis.text = element_text(size=9))

library(gridExtra)
grid.arrange(p1,p2,p3,p4,p5, nrow=1)
@
\end{center}

Let's compare if we have within and/or among-patient correlations in $\phi$ for example. I subsetted only 15 patients for clarity:

<<>>=
Among <- sim_func(raP1P2 = 0.8)
Both <- sim_func(raP1P2 = 0.8, rwP1P2 = -0.9)
@

\begin{center}
<<fig=T, echo=F, height=4, width=8>>=
a1 <- subset(Among, Strain == 1)
a2 <- subset(Among, Strain == 2)

among <- cbind(a2$phi, a1$phi, a1[,6])
colnames(among) <- c("phi2", "phi1", "Pat")
among <- data.frame(among)
among <- subset(among, Pat < 16)

p1 <- ggplot(among, aes(x=phi1, y=phi2, color=factor(Pat)))+
  geom_point()+
  theme(legend.position = "none")+
  scale_y_continuous(limits=c(0,1), breaks=c(0,.5,1))+
  scale_x_continuous(limits=c(0,1), breaks=c(0,.5,1))+
  labs(x = expression(paste(phi, " Strain 1")), y = expression(paste(phi, " Strain 2")))+
  ggtitle("Only Among-patient Corr")

b1 <- subset(Both, Strain == 1)
b2 <- subset(Both, Strain == 2)

both <- cbind(b2$phi, b1$phi, b1[,6])
colnames(both) <- c("phi2", "phi1", "Pat")
both <- data.frame(both)
both <- subset(both, Pat < 16)

p2 <- ggplot(both, aes(x=phi1, y=phi2, color=factor(Pat)))+
  geom_point()+
  theme(legend.position = "none")+
  scale_y_continuous(limits=c(0,1), breaks=c(0,.5,1))+
  scale_x_continuous(limits=c(0,1), breaks=c(0,.5,1))+
  labs(x = expression(paste(phi, " Strain 1")), y = expression(paste(phi, " Strain 2")))+
  ggtitle("Both Corr")

grid.arrange(p1,p2, ncol=2)              
@
\end{center}

In the above figure, you can see that, with among-patient correlations, the $\phi$ values are grouped by patient (color), but there is random spread within the color grouping. However, when there is both within- and among-patient correlations, $\phi$ values are grouped by patient, but also the within-patient correlation is visible. You can alter the within and among correlations to be positive or negative and see what the figure looks like. For instance, you can generate Simpson's paradox with correlatinos of different sign. 

\end{document}






