#!/bin/bash

########################
#                      #
# Scheduler Directives #
#                      #
########################

### Set the name of the job, where jobname is a unique name for your job
#PBS -N HPV_test

### Select the shell you would like the script to execute within
#PBS -S /bin/bash

### Inform the scheduler of the expected runtime, where walltime=HH:MM:SS
#PBS -l walltime=168:00:00

### Inform the scheduler of the number of CPU cores for your job.
### This example will allocate four cores on a single node.
#PBS -l nodes=1:ppn=3

### Inform the scheduler of the amount of memory you expect to use.
### Use units of 'b', 'kb', 'mb', or 'gb'
#PBS -l mem=6gb

### Set the destination for your program's output.
#PBS -o $HOME/HPV_fit.out
#PBS -e $HOME/HPV_fit.err


#################
#               #
# Job Execution #
#               #
#################

# Load the approprite applications
module load R/3.3.1

# Execute the program
R CMD BATCH fit_model_MDW.R